/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ClubsClubIdRouteImport } from './routes/clubs.$clubId'
import { Route as ClubSplatRouteImport } from './routes/club.$'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSellRouteImport } from './routes/app.sell'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppManageRouteImport } from './routes/app.manage'
import { Route as AppGettingStartedRouteImport } from './routes/app.getting-started'
import { Route as AppCustomizeRouteImport } from './routes/app.customize'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppBookmarksRouteImport } from './routes/app.bookmarks'
import { Route as AppAppsRouteImport } from './routes/app.apps'
import { Route as AppAivaRouteImport } from './routes/app.aiva'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AppSettingsIndexRouteImport } from './routes/app.settings.index'
import { Route as AppSellIndexRouteImport } from './routes/app.sell.index'
import { Route as AppManageIndexRouteImport } from './routes/app.manage.index'
import { Route as AppAppsIndexRouteImport } from './routes/app.apps.index'
import { Route as AppSettingsNavigationRouteImport } from './routes/app.settings.navigation'
import { Route as AppSettingsAiPersonaRouteImport } from './routes/app.settings.ai-persona'
import { Route as AppSettingsSectionRouteImport } from './routes/app.settings.$section'
import { Route as AppSellPageIdRouteImport } from './routes/app.sell.$pageId'
import { Route as AppPagePageIdRouteImport } from './routes/app.page.$pageId'
import { Route as AppManagePersonaRouteImport } from './routes/app.manage.persona'
import { Route as AppManageNavigationRouteImport } from './routes/app.manage.navigation'
import { Route as AppClubSettingsRouteImport } from './routes/app.club.settings'
import { Route as AppClubResourcesRouteImport } from './routes/app.club.resources'
import { Route as AppClubMembersRouteImport } from './routes/app.club.members'
import { Route as AppClubLeaderboardRouteImport } from './routes/app.club.leaderboard'
import { Route as AppClubFeedRouteImport } from './routes/app.club.feed'
import { Route as AppClubEventsRouteImport } from './routes/app.club.events'
import { Route as AppClubCoursesRouteImport } from './routes/app.club.courses'
import { Route as AppClubCoachingRouteImport } from './routes/app.club.coaching'
import { Route as AppClubChallengesRouteImport } from './routes/app.club.challenges'
import { Route as AppClubAnalyticsRouteImport } from './routes/app.club.analytics'
import { Route as AppAppsAppIdRouteImport } from './routes/app.apps.$appId'
import { Route as AppAppsAppIdIndexRouteImport } from './routes/app.apps.$appId.index'
import { Route as AppAppsAppIdEditRouteImport } from './routes/app.apps.$appId.edit'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsClubIdRoute = ClubsClubIdRouteImport.update({
  id: '/clubs/$clubId',
  path: '/clubs/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubSplatRoute = ClubSplatRouteImport.update({
  id: '/club/$',
  path: '/club/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSellRoute = AppSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppManageRoute = AppManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AppRoute,
} as any)
const AppGettingStartedRoute = AppGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomizeRoute = AppCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsRoute = AppAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AppRoute,
} as any)
const AppAivaRoute = AppAivaRouteImport.update({
  id: '/aiva',
  path: '/aiva',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSellIndexRoute = AppSellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSellRoute,
} as any)
const AppManageIndexRoute = AppManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppManageRoute,
} as any)
const AppAppsIndexRoute = AppAppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppsRoute,
} as any)
const AppSettingsNavigationRoute = AppSettingsNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAiPersonaRoute = AppSettingsAiPersonaRouteImport.update({
  id: '/ai-persona',
  path: '/ai-persona',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSectionRoute = AppSettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSellPageIdRoute = AppSellPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => AppSellRoute,
} as any)
const AppPagePageIdRoute = AppPagePageIdRouteImport.update({
  id: '/page/$pageId',
  path: '/page/$pageId',
  getParentRoute: () => AppRoute,
} as any)
const AppManagePersonaRoute = AppManagePersonaRouteImport.update({
  id: '/persona',
  path: '/persona',
  getParentRoute: () => AppManageRoute,
} as any)
const AppManageNavigationRoute = AppManageNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AppManageRoute,
} as any)
const AppClubSettingsRoute = AppClubSettingsRouteImport.update({
  id: '/club/settings',
  path: '/club/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppClubResourcesRoute = AppClubResourcesRouteImport.update({
  id: '/club/resources',
  path: '/club/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppClubMembersRoute = AppClubMembersRouteImport.update({
  id: '/club/members',
  path: '/club/members',
  getParentRoute: () => AppRoute,
} as any)
const AppClubLeaderboardRoute = AppClubLeaderboardRouteImport.update({
  id: '/club/leaderboard',
  path: '/club/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClubFeedRoute = AppClubFeedRouteImport.update({
  id: '/club/feed',
  path: '/club/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppClubEventsRoute = AppClubEventsRouteImport.update({
  id: '/club/events',
  path: '/club/events',
  getParentRoute: () => AppRoute,
} as any)
const AppClubCoursesRoute = AppClubCoursesRouteImport.update({
  id: '/club/courses',
  path: '/club/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppClubCoachingRoute = AppClubCoachingRouteImport.update({
  id: '/club/coaching',
  path: '/club/coaching',
  getParentRoute: () => AppRoute,
} as any)
const AppClubChallengesRoute = AppClubChallengesRouteImport.update({
  id: '/club/challenges',
  path: '/club/challenges',
  getParentRoute: () => AppRoute,
} as any)
const AppClubAnalyticsRoute = AppClubAnalyticsRouteImport.update({
  id: '/club/analytics',
  path: '/club/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsAppIdRoute = AppAppsAppIdRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => AppAppsRoute,
} as any)
const AppAppsAppIdIndexRoute = AppAppsAppIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdEditRoute = AppAppsAppIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/app/account': typeof AppAccountRoute
  '/app/aiva': typeof AppAivaRoute
  '/app/apps': typeof AppAppsRouteWithChildren
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/customize': typeof AppCustomizeRoute
  '/app/getting-started': typeof AppGettingStartedRoute
  '/app/manage': typeof AppManageRouteWithChildren
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/sell': typeof AppSellRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/club/$': typeof ClubSplatRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/p/$slug': typeof PSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/apps/$appId': typeof AppAppsAppIdRouteWithChildren
  '/app/club/analytics': typeof AppClubAnalyticsRoute
  '/app/club/challenges': typeof AppClubChallengesRoute
  '/app/club/coaching': typeof AppClubCoachingRoute
  '/app/club/courses': typeof AppClubCoursesRoute
  '/app/club/events': typeof AppClubEventsRoute
  '/app/club/feed': typeof AppClubFeedRoute
  '/app/club/leaderboard': typeof AppClubLeaderboardRoute
  '/app/club/members': typeof AppClubMembersRoute
  '/app/club/resources': typeof AppClubResourcesRoute
  '/app/club/settings': typeof AppClubSettingsRoute
  '/app/manage/navigation': typeof AppManageNavigationRoute
  '/app/manage/persona': typeof AppManagePersonaRoute
  '/app/page/$pageId': typeof AppPagePageIdRoute
  '/app/sell/$pageId': typeof AppSellPageIdRoute
  '/app/settings/$section': typeof AppSettingsSectionRoute
  '/app/settings/ai-persona': typeof AppSettingsAiPersonaRoute
  '/app/settings/navigation': typeof AppSettingsNavigationRoute
  '/app/apps/': typeof AppAppsIndexRoute
  '/app/manage/': typeof AppManageIndexRoute
  '/app/sell/': typeof AppSellIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/app/apps/$appId/edit': typeof AppAppsAppIdEditRoute
  '/app/apps/$appId/': typeof AppAppsAppIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/app/account': typeof AppAccountRoute
  '/app/aiva': typeof AppAivaRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/customize': typeof AppCustomizeRoute
  '/app/getting-started': typeof AppGettingStartedRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/club/$': typeof ClubSplatRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/p/$slug': typeof PSlugRoute
  '/app': typeof AppIndexRoute
  '/app/club/analytics': typeof AppClubAnalyticsRoute
  '/app/club/challenges': typeof AppClubChallengesRoute
  '/app/club/coaching': typeof AppClubCoachingRoute
  '/app/club/courses': typeof AppClubCoursesRoute
  '/app/club/events': typeof AppClubEventsRoute
  '/app/club/feed': typeof AppClubFeedRoute
  '/app/club/leaderboard': typeof AppClubLeaderboardRoute
  '/app/club/members': typeof AppClubMembersRoute
  '/app/club/resources': typeof AppClubResourcesRoute
  '/app/club/settings': typeof AppClubSettingsRoute
  '/app/manage/navigation': typeof AppManageNavigationRoute
  '/app/manage/persona': typeof AppManagePersonaRoute
  '/app/page/$pageId': typeof AppPagePageIdRoute
  '/app/sell/$pageId': typeof AppSellPageIdRoute
  '/app/settings/$section': typeof AppSettingsSectionRoute
  '/app/settings/ai-persona': typeof AppSettingsAiPersonaRoute
  '/app/settings/navigation': typeof AppSettingsNavigationRoute
  '/app/apps': typeof AppAppsIndexRoute
  '/app/manage': typeof AppManageIndexRoute
  '/app/sell': typeof AppSellIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/app/apps/$appId/edit': typeof AppAppsAppIdEditRoute
  '/app/apps/$appId': typeof AppAppsAppIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/app/account': typeof AppAccountRoute
  '/app/aiva': typeof AppAivaRoute
  '/app/apps': typeof AppAppsRouteWithChildren
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/customize': typeof AppCustomizeRoute
  '/app/getting-started': typeof AppGettingStartedRoute
  '/app/manage': typeof AppManageRouteWithChildren
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/sell': typeof AppSellRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/club/$': typeof ClubSplatRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/p/$slug': typeof PSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/apps/$appId': typeof AppAppsAppIdRouteWithChildren
  '/app/club/analytics': typeof AppClubAnalyticsRoute
  '/app/club/challenges': typeof AppClubChallengesRoute
  '/app/club/coaching': typeof AppClubCoachingRoute
  '/app/club/courses': typeof AppClubCoursesRoute
  '/app/club/events': typeof AppClubEventsRoute
  '/app/club/feed': typeof AppClubFeedRoute
  '/app/club/leaderboard': typeof AppClubLeaderboardRoute
  '/app/club/members': typeof AppClubMembersRoute
  '/app/club/resources': typeof AppClubResourcesRoute
  '/app/club/settings': typeof AppClubSettingsRoute
  '/app/manage/navigation': typeof AppManageNavigationRoute
  '/app/manage/persona': typeof AppManagePersonaRoute
  '/app/page/$pageId': typeof AppPagePageIdRoute
  '/app/sell/$pageId': typeof AppSellPageIdRoute
  '/app/settings/$section': typeof AppSettingsSectionRoute
  '/app/settings/ai-persona': typeof AppSettingsAiPersonaRoute
  '/app/settings/navigation': typeof AppSettingsNavigationRoute
  '/app/apps/': typeof AppAppsIndexRoute
  '/app/manage/': typeof AppManageIndexRoute
  '/app/sell/': typeof AppSellIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/app/apps/$appId/edit': typeof AppAppsAppIdEditRoute
  '/app/apps/$appId/': typeof AppAppsAppIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/discover'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/app/account'
    | '/app/aiva'
    | '/app/apps'
    | '/app/bookmarks'
    | '/app/calendar'
    | '/app/customize'
    | '/app/getting-started'
    | '/app/manage'
    | '/app/messages'
    | '/app/notifications'
    | '/app/sell'
    | '/app/settings'
    | '/club/$'
    | '/clubs/$clubId'
    | '/p/$slug'
    | '/app/'
    | '/app/apps/$appId'
    | '/app/club/analytics'
    | '/app/club/challenges'
    | '/app/club/coaching'
    | '/app/club/courses'
    | '/app/club/events'
    | '/app/club/feed'
    | '/app/club/leaderboard'
    | '/app/club/members'
    | '/app/club/resources'
    | '/app/club/settings'
    | '/app/manage/navigation'
    | '/app/manage/persona'
    | '/app/page/$pageId'
    | '/app/sell/$pageId'
    | '/app/settings/$section'
    | '/app/settings/ai-persona'
    | '/app/settings/navigation'
    | '/app/apps/'
    | '/app/manage/'
    | '/app/sell/'
    | '/app/settings/'
    | '/api/public/webhooks/stripe'
    | '/app/apps/$appId/edit'
    | '/app/apps/$appId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/app/account'
    | '/app/aiva'
    | '/app/bookmarks'
    | '/app/calendar'
    | '/app/customize'
    | '/app/getting-started'
    | '/app/messages'
    | '/app/notifications'
    | '/club/$'
    | '/clubs/$clubId'
    | '/p/$slug'
    | '/app'
    | '/app/club/analytics'
    | '/app/club/challenges'
    | '/app/club/coaching'
    | '/app/club/courses'
    | '/app/club/events'
    | '/app/club/feed'
    | '/app/club/leaderboard'
    | '/app/club/members'
    | '/app/club/resources'
    | '/app/club/settings'
    | '/app/manage/navigation'
    | '/app/manage/persona'
    | '/app/page/$pageId'
    | '/app/sell/$pageId'
    | '/app/settings/$section'
    | '/app/settings/ai-persona'
    | '/app/settings/navigation'
    | '/app/apps'
    | '/app/manage'
    | '/app/sell'
    | '/app/settings'
    | '/api/public/webhooks/stripe'
    | '/app/apps/$appId/edit'
    | '/app/apps/$appId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/discover'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/app/account'
    | '/app/aiva'
    | '/app/apps'
    | '/app/bookmarks'
    | '/app/calendar'
    | '/app/customize'
    | '/app/getting-started'
    | '/app/manage'
    | '/app/messages'
    | '/app/notifications'
    | '/app/sell'
    | '/app/settings'
    | '/club/$'
    | '/clubs/$clubId'
    | '/p/$slug'
    | '/app/'
    | '/app/apps/$appId'
    | '/app/club/analytics'
    | '/app/club/challenges'
    | '/app/club/coaching'
    | '/app/club/courses'
    | '/app/club/events'
    | '/app/club/feed'
    | '/app/club/leaderboard'
    | '/app/club/members'
    | '/app/club/resources'
    | '/app/club/settings'
    | '/app/manage/navigation'
    | '/app/manage/persona'
    | '/app/page/$pageId'
    | '/app/sell/$pageId'
    | '/app/settings/$section'
    | '/app/settings/ai-persona'
    | '/app/settings/navigation'
    | '/app/apps/'
    | '/app/manage/'
    | '/app/sell/'
    | '/app/settings/'
    | '/api/public/webhooks/stripe'
    | '/app/apps/$appId/edit'
    | '/app/apps/$appId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  ClubSplatRoute: typeof ClubSplatRoute
  ClubsClubIdRoute: typeof ClubsClubIdRoute
  PSlugRoute: typeof PSlugRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$clubId': {
      id: '/clubs/$clubId'
      path: '/clubs/$clubId'
      fullPath: '/clubs/$clubId'
      preLoaderRoute: typeof ClubsClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/$': {
      id: '/club/$'
      path: '/club/$'
      fullPath: '/club/$'
      preLoaderRoute: typeof ClubSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sell': {
      id: '/app/sell'
      path: '/sell'
      fullPath: '/app/sell'
      preLoaderRoute: typeof AppSellRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manage': {
      id: '/app/manage'
      path: '/manage'
      fullPath: '/app/manage'
      preLoaderRoute: typeof AppManageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/getting-started': {
      id: '/app/getting-started'
      path: '/getting-started'
      fullPath: '/app/getting-started'
      preLoaderRoute: typeof AppGettingStartedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customize': {
      id: '/app/customize'
      path: '/customize'
      fullPath: '/app/customize'
      preLoaderRoute: typeof AppCustomizeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookmarks': {
      id: '/app/bookmarks'
      path: '/bookmarks'
      fullPath: '/app/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/apps': {
      id: '/app/apps'
      path: '/apps'
      fullPath: '/app/apps'
      preLoaderRoute: typeof AppAppsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aiva': {
      id: '/app/aiva'
      path: '/aiva'
      fullPath: '/app/aiva'
      preLoaderRoute: typeof AppAivaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/sell/': {
      id: '/app/sell/'
      path: '/'
      fullPath: '/app/sell/'
      preLoaderRoute: typeof AppSellIndexRouteImport
      parentRoute: typeof AppSellRoute
    }
    '/app/manage/': {
      id: '/app/manage/'
      path: '/'
      fullPath: '/app/manage/'
      preLoaderRoute: typeof AppManageIndexRouteImport
      parentRoute: typeof AppManageRoute
    }
    '/app/apps/': {
      id: '/app/apps/'
      path: '/'
      fullPath: '/app/apps/'
      preLoaderRoute: typeof AppAppsIndexRouteImport
      parentRoute: typeof AppAppsRoute
    }
    '/app/settings/navigation': {
      id: '/app/settings/navigation'
      path: '/navigation'
      fullPath: '/app/settings/navigation'
      preLoaderRoute: typeof AppSettingsNavigationRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/ai-persona': {
      id: '/app/settings/ai-persona'
      path: '/ai-persona'
      fullPath: '/app/settings/ai-persona'
      preLoaderRoute: typeof AppSettingsAiPersonaRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/$section': {
      id: '/app/settings/$section'
      path: '/$section'
      fullPath: '/app/settings/$section'
      preLoaderRoute: typeof AppSettingsSectionRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/sell/$pageId': {
      id: '/app/sell/$pageId'
      path: '/$pageId'
      fullPath: '/app/sell/$pageId'
      preLoaderRoute: typeof AppSellPageIdRouteImport
      parentRoute: typeof AppSellRoute
    }
    '/app/page/$pageId': {
      id: '/app/page/$pageId'
      path: '/page/$pageId'
      fullPath: '/app/page/$pageId'
      preLoaderRoute: typeof AppPagePageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manage/persona': {
      id: '/app/manage/persona'
      path: '/persona'
      fullPath: '/app/manage/persona'
      preLoaderRoute: typeof AppManagePersonaRouteImport
      parentRoute: typeof AppManageRoute
    }
    '/app/manage/navigation': {
      id: '/app/manage/navigation'
      path: '/navigation'
      fullPath: '/app/manage/navigation'
      preLoaderRoute: typeof AppManageNavigationRouteImport
      parentRoute: typeof AppManageRoute
    }
    '/app/club/settings': {
      id: '/app/club/settings'
      path: '/club/settings'
      fullPath: '/app/club/settings'
      preLoaderRoute: typeof AppClubSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club/resources': {
      id: '/app/club/resources'
      path: '/club/resources'
      fullPath: '/app/club/resources'
      preLoaderRoute: typeof AppClubResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club/members': {
      id: '/app/club/members'
      path: '/club/members'
      fullPath: '/app/club/members'
      preLoaderRoute: typeof AppClubMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club/leaderboard': {
      id: '/app/club/leaderboard'
      path: '/club/leaderboard'
      fullPath: '/app/club/leaderboard'
      preLoaderRoute: typeof AppClubLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club/feed': {
      id: '/app/club/feed'
      path: '/club/feed'
      fullPath: '/app/club/feed'
      preLoaderRoute: typeof AppClubFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club/events': {
      id: '/app/club/events'
      path: '/club/events'
      fullPath: '/app/club/events'
      preLoaderRoute: typeof AppClubEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club/courses': {
      id: '/app/club/courses'
      path: '/club/courses'
      fullPath: '/app/club/courses'
      preLoaderRoute: typeof AppClubCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club/coaching': {
      id: '/app/club/coaching'
      path: '/club/coaching'
      fullPath: '/app/club/coaching'
      preLoaderRoute: typeof AppClubCoachingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club/challenges': {
      id: '/app/club/challenges'
      path: '/club/challenges'
      fullPath: '/app/club/challenges'
      preLoaderRoute: typeof AppClubChallengesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club/analytics': {
      id: '/app/club/analytics'
      path: '/club/analytics'
      fullPath: '/app/club/analytics'
      preLoaderRoute: typeof AppClubAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/apps/$appId': {
      id: '/app/apps/$appId'
      path: '/$appId'
      fullPath: '/app/apps/$appId'
      preLoaderRoute: typeof AppAppsAppIdRouteImport
      parentRoute: typeof AppAppsRoute
    }
    '/app/apps/$appId/': {
      id: '/app/apps/$appId/'
      path: '/'
      fullPath: '/app/apps/$appId/'
      preLoaderRoute: typeof AppAppsAppIdIndexRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/app/apps/$appId/edit': {
      id: '/app/apps/$appId/edit'
      path: '/edit'
      fullPath: '/app/apps/$appId/edit'
      preLoaderRoute: typeof AppAppsAppIdEditRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAppsAppIdRouteChildren {
  AppAppsAppIdEditRoute: typeof AppAppsAppIdEditRoute
  AppAppsAppIdIndexRoute: typeof AppAppsAppIdIndexRoute
}

const AppAppsAppIdRouteChildren: AppAppsAppIdRouteChildren = {
  AppAppsAppIdEditRoute: AppAppsAppIdEditRoute,
  AppAppsAppIdIndexRoute: AppAppsAppIdIndexRoute,
}

const AppAppsAppIdRouteWithChildren = AppAppsAppIdRoute._addFileChildren(
  AppAppsAppIdRouteChildren,
)

interface AppAppsRouteChildren {
  AppAppsAppIdRoute: typeof AppAppsAppIdRouteWithChildren
  AppAppsIndexRoute: typeof AppAppsIndexRoute
}

const AppAppsRouteChildren: AppAppsRouteChildren = {
  AppAppsAppIdRoute: AppAppsAppIdRouteWithChildren,
  AppAppsIndexRoute: AppAppsIndexRoute,
}

const AppAppsRouteWithChildren =
  AppAppsRoute._addFileChildren(AppAppsRouteChildren)

interface AppManageRouteChildren {
  AppManageNavigationRoute: typeof AppManageNavigationRoute
  AppManagePersonaRoute: typeof AppManagePersonaRoute
  AppManageIndexRoute: typeof AppManageIndexRoute
}

const AppManageRouteChildren: AppManageRouteChildren = {
  AppManageNavigationRoute: AppManageNavigationRoute,
  AppManagePersonaRoute: AppManagePersonaRoute,
  AppManageIndexRoute: AppManageIndexRoute,
}

const AppManageRouteWithChildren = AppManageRoute._addFileChildren(
  AppManageRouteChildren,
)

interface AppSellRouteChildren {
  AppSellPageIdRoute: typeof AppSellPageIdRoute
  AppSellIndexRoute: typeof AppSellIndexRoute
}

const AppSellRouteChildren: AppSellRouteChildren = {
  AppSellPageIdRoute: AppSellPageIdRoute,
  AppSellIndexRoute: AppSellIndexRoute,
}

const AppSellRouteWithChildren =
  AppSellRoute._addFileChildren(AppSellRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsSectionRoute: typeof AppSettingsSectionRoute
  AppSettingsAiPersonaRoute: typeof AppSettingsAiPersonaRoute
  AppSettingsNavigationRoute: typeof AppSettingsNavigationRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsSectionRoute: AppSettingsSectionRoute,
  AppSettingsAiPersonaRoute: AppSettingsAiPersonaRoute,
  AppSettingsNavigationRoute: AppSettingsNavigationRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAivaRoute: typeof AppAivaRoute
  AppAppsRoute: typeof AppAppsRouteWithChildren
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCustomizeRoute: typeof AppCustomizeRoute
  AppGettingStartedRoute: typeof AppGettingStartedRoute
  AppManageRoute: typeof AppManageRouteWithChildren
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSellRoute: typeof AppSellRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppClubAnalyticsRoute: typeof AppClubAnalyticsRoute
  AppClubChallengesRoute: typeof AppClubChallengesRoute
  AppClubCoachingRoute: typeof AppClubCoachingRoute
  AppClubCoursesRoute: typeof AppClubCoursesRoute
  AppClubEventsRoute: typeof AppClubEventsRoute
  AppClubFeedRoute: typeof AppClubFeedRoute
  AppClubLeaderboardRoute: typeof AppClubLeaderboardRoute
  AppClubMembersRoute: typeof AppClubMembersRoute
  AppClubResourcesRoute: typeof AppClubResourcesRoute
  AppClubSettingsRoute: typeof AppClubSettingsRoute
  AppPagePageIdRoute: typeof AppPagePageIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAivaRoute: AppAivaRoute,
  AppAppsRoute: AppAppsRouteWithChildren,
  AppBookmarksRoute: AppBookmarksRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCustomizeRoute: AppCustomizeRoute,
  AppGettingStartedRoute: AppGettingStartedRoute,
  AppManageRoute: AppManageRouteWithChildren,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSellRoute: AppSellRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppClubAnalyticsRoute: AppClubAnalyticsRoute,
  AppClubChallengesRoute: AppClubChallengesRoute,
  AppClubCoachingRoute: AppClubCoachingRoute,
  AppClubCoursesRoute: AppClubCoursesRoute,
  AppClubEventsRoute: AppClubEventsRoute,
  AppClubFeedRoute: AppClubFeedRoute,
  AppClubLeaderboardRoute: AppClubLeaderboardRoute,
  AppClubMembersRoute: AppClubMembersRoute,
  AppClubResourcesRoute: AppClubResourcesRoute,
  AppClubSettingsRoute: AppClubSettingsRoute,
  AppPagePageIdRoute: AppPagePageIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  ClubSplatRoute: ClubSplatRoute,
  ClubsClubIdRoute: ClubsClubIdRoute,
  PSlugRoute: PSlugRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
