/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ClubSplatRouteImport } from './routes/club.$'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppGettingStartedRouteImport } from './routes/app.getting-started'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppBookmarksRouteImport } from './routes/app.bookmarks'
import { Route as AppAivaRouteImport } from './routes/app.aiva'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AppClubSettingsRouteImport } from './routes/app.club.settings'
import { Route as AppClubMembersRouteImport } from './routes/app.club.members'
import { Route as AppClubFeedRouteImport } from './routes/app.club.feed'
import { Route as AppClubEventsRouteImport } from './routes/app.club.events'
import { Route as AppClubCoursesRouteImport } from './routes/app.club.courses'
import { Route as AppClubChallengesRouteImport } from './routes/app.club.challenges'
import { Route as AppClubAnalyticsRouteImport } from './routes/app.club.analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ClubSplatRoute = ClubSplatRouteImport.update({
  id: '/club/$',
  path: '/club/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppGettingStartedRoute = AppGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRoute,
} as any)
const AppAivaRoute = AppAivaRouteImport.update({
  id: '/aiva',
  path: '/aiva',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppClubSettingsRoute = AppClubSettingsRouteImport.update({
  id: '/club/settings',
  path: '/club/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppClubMembersRoute = AppClubMembersRouteImport.update({
  id: '/club/members',
  path: '/club/members',
  getParentRoute: () => AppRoute,
} as any)
const AppClubFeedRoute = AppClubFeedRouteImport.update({
  id: '/club/feed',
  path: '/club/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppClubEventsRoute = AppClubEventsRouteImport.update({
  id: '/club/events',
  path: '/club/events',
  getParentRoute: () => AppRoute,
} as any)
const AppClubCoursesRoute = AppClubCoursesRouteImport.update({
  id: '/club/courses',
  path: '/club/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppClubChallengesRoute = AppClubChallengesRouteImport.update({
  id: '/club/challenges',
  path: '/club/challenges',
  getParentRoute: () => AppRoute,
} as any)
const AppClubAnalyticsRoute = AppClubAnalyticsRouteImport.update({
  id: '/club/analytics',
  path: '/club/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/account': typeof AppAccountRoute
  '/app/aiva': typeof AppAivaRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/getting-started': typeof AppGettingStartedRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/club/$': typeof ClubSplatRoute
  '/app/': typeof AppIndexRoute
  '/app/club/analytics': typeof AppClubAnalyticsRoute
  '/app/club/challenges': typeof AppClubChallengesRoute
  '/app/club/courses': typeof AppClubCoursesRoute
  '/app/club/events': typeof AppClubEventsRoute
  '/app/club/feed': typeof AppClubFeedRoute
  '/app/club/members': typeof AppClubMembersRoute
  '/app/club/settings': typeof AppClubSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/account': typeof AppAccountRoute
  '/app/aiva': typeof AppAivaRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/getting-started': typeof AppGettingStartedRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/club/$': typeof ClubSplatRoute
  '/app': typeof AppIndexRoute
  '/app/club/analytics': typeof AppClubAnalyticsRoute
  '/app/club/challenges': typeof AppClubChallengesRoute
  '/app/club/courses': typeof AppClubCoursesRoute
  '/app/club/events': typeof AppClubEventsRoute
  '/app/club/feed': typeof AppClubFeedRoute
  '/app/club/members': typeof AppClubMembersRoute
  '/app/club/settings': typeof AppClubSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/account': typeof AppAccountRoute
  '/app/aiva': typeof AppAivaRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/getting-started': typeof AppGettingStartedRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/club/$': typeof ClubSplatRoute
  '/app/': typeof AppIndexRoute
  '/app/club/analytics': typeof AppClubAnalyticsRoute
  '/app/club/challenges': typeof AppClubChallengesRoute
  '/app/club/courses': typeof AppClubCoursesRoute
  '/app/club/events': typeof AppClubEventsRoute
  '/app/club/feed': typeof AppClubFeedRoute
  '/app/club/members': typeof AppClubMembersRoute
  '/app/club/settings': typeof AppClubSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/discover'
    | '/landing'
    | '/login'
    | '/signup'
    | '/app/account'
    | '/app/aiva'
    | '/app/bookmarks'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/getting-started'
    | '/app/messages'
    | '/app/notifications'
    | '/club/$'
    | '/app/'
    | '/app/club/analytics'
    | '/app/club/challenges'
    | '/app/club/courses'
    | '/app/club/events'
    | '/app/club/feed'
    | '/app/club/members'
    | '/app/club/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/landing'
    | '/login'
    | '/signup'
    | '/app/account'
    | '/app/aiva'
    | '/app/bookmarks'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/getting-started'
    | '/app/messages'
    | '/app/notifications'
    | '/club/$'
    | '/app'
    | '/app/club/analytics'
    | '/app/club/challenges'
    | '/app/club/courses'
    | '/app/club/events'
    | '/app/club/feed'
    | '/app/club/members'
    | '/app/club/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/discover'
    | '/landing'
    | '/login'
    | '/signup'
    | '/app/account'
    | '/app/aiva'
    | '/app/bookmarks'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/getting-started'
    | '/app/messages'
    | '/app/notifications'
    | '/club/$'
    | '/app/'
    | '/app/club/analytics'
    | '/app/club/challenges'
    | '/app/club/courses'
    | '/app/club/events'
    | '/app/club/feed'
    | '/app/club/members'
    | '/app/club/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ClubSplatRoute: typeof ClubSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/club/$': {
      id: '/club/$'
      path: '/club/$'
      fullPath: '/club/$'
      preLoaderRoute: typeof ClubSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/getting-started': {
      id: '/app/getting-started'
      path: '/getting-started'
      fullPath: '/app/getting-started'
      preLoaderRoute: typeof AppGettingStartedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookmarks': {
      id: '/app/bookmarks'
      path: '/bookmarks'
      fullPath: '/app/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aiva': {
      id: '/app/aiva'
      path: '/aiva'
      fullPath: '/app/aiva'
      preLoaderRoute: typeof AppAivaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club/settings': {
      id: '/app/club/settings'
      path: '/club/settings'
      fullPath: '/app/club/settings'
      preLoaderRoute: typeof AppClubSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club/members': {
      id: '/app/club/members'
      path: '/club/members'
      fullPath: '/app/club/members'
      preLoaderRoute: typeof AppClubMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club/feed': {
      id: '/app/club/feed'
      path: '/club/feed'
      fullPath: '/app/club/feed'
      preLoaderRoute: typeof AppClubFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club/events': {
      id: '/app/club/events'
      path: '/club/events'
      fullPath: '/app/club/events'
      preLoaderRoute: typeof AppClubEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club/courses': {
      id: '/app/club/courses'
      path: '/club/courses'
      fullPath: '/app/club/courses'
      preLoaderRoute: typeof AppClubCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club/challenges': {
      id: '/app/club/challenges'
      path: '/club/challenges'
      fullPath: '/app/club/challenges'
      preLoaderRoute: typeof AppClubChallengesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club/analytics': {
      id: '/app/club/analytics'
      path: '/club/analytics'
      fullPath: '/app/club/analytics'
      preLoaderRoute: typeof AppClubAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAivaRoute: typeof AppAivaRoute
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGettingStartedRoute: typeof AppGettingStartedRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClubAnalyticsRoute: typeof AppClubAnalyticsRoute
  AppClubChallengesRoute: typeof AppClubChallengesRoute
  AppClubCoursesRoute: typeof AppClubCoursesRoute
  AppClubEventsRoute: typeof AppClubEventsRoute
  AppClubFeedRoute: typeof AppClubFeedRoute
  AppClubMembersRoute: typeof AppClubMembersRoute
  AppClubSettingsRoute: typeof AppClubSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAivaRoute: AppAivaRoute,
  AppBookmarksRoute: AppBookmarksRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGettingStartedRoute: AppGettingStartedRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppIndexRoute: AppIndexRoute,
  AppClubAnalyticsRoute: AppClubAnalyticsRoute,
  AppClubChallengesRoute: AppClubChallengesRoute,
  AppClubCoursesRoute: AppClubCoursesRoute,
  AppClubEventsRoute: AppClubEventsRoute,
  AppClubFeedRoute: AppClubFeedRoute,
  AppClubMembersRoute: AppClubMembersRoute,
  AppClubSettingsRoute: AppClubSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ClubSplatRoute: ClubSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
